# Generated by Django 4.1.3 on 2022-11-25 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_author_remove_comment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='publications.publication'),
            preserve_default=False,
        ),
    ]
