# Generated by Django 4.1.3 on 2022-11-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='coment_likes',
        ),
    ]
