# Generated by Django 4.1.3 on 2022-11-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_remove_comment_author_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
